<?php
use App\Product;
use Illuminate\Database\Seeder;

class ProductTableSeeder extends Seeder
{
  	public function run()
  	{
        Product::create(['name' => 'BANGUS','slug' => 'bangus','sku' => 'FF0001','price' => '10','qty' => 1,'category_id' => 6,'status' =>1,'image' => '',]);
        Product::create(['name' => 'TILAPIA','slug' => 'tilapia','sku' => 'FF0002','price' => '10','qty' => 1,'category_id' => 6,'status' =>1,'image' => '',]);
        Product::create(['name' => 'GALUNGGONG','slug' => 'galunggong','sku' => 'FF0003','price' => '10','qty' => 1,'category_id' => 6,'status' =>1,'image' => '',]);
        Product::create(['name' => 'DALAGANG BUKID','slug' => 'dalagang-bukid','sku' => 'FF0004','price' => '10','qty' => 1,'category_id' => 6,'status' =>1,'image' => '',]);
        Product::create(['name' => 'SAPSAP','slug' => 'sapsap','sku' => 'FF0005','price' => '10','qty' => 1,'category_id' => 6,'status' =>1,'image' => '',]);
        Product::create(['name' => 'BISUGO','slug' => 'bisugo','sku' => 'FF0006','price' => '10','qty' => 1,'category_id' => 6,'status' =>1,'image' => '',]);
        Product::create(['name' => 'TORSILYO','slug' => 'torsilyo','sku' => 'FF0007','price' => '10','qty' => 1,'category_id' => 6,'status' =>1,'image' => '',]);
        Product::create(['name' => 'DILIS','slug' => 'dilis','sku' => 'FF0008','price' => '10','qty' => 1,'category_id' => 6,'status' =>1,'image' => '',]);
        Product::create(['name' => 'TAMBAN','slug' => 'tamban','sku' => 'FF0009','price' => '10','qty' => 1,'category_id' => 6,'status' =>1,'image' => '',]);
        Product::create(['name' => 'TAWILIS','slug' => 'tawilis','sku' => 'FF0010','price' => '10','qty' => 1,'category_id' => 6,'status' =>1,'image' => '',]);
        Product::create(['name' => 'TULINGAN','slug' => 'tulingan','sku' => 'FF0011','price' => '10','qty' => 1,'category_id' => 6,'status' =>1,'image' => '',]);
        Product::create(['name' => 'TAMBAKOL','slug' => 'tambakol','sku' => 'FF0012','price' => '10','qty' => 1,'category_id' => 6,'status' =>1,'image' => '',]);
        Product::create(['name' => 'TANIGUI','slug' => 'tanigui','sku' => 'FF0013','price' => '10','qty' => 1,'category_id' => 6,'status' =>1,'image' => '',]);
        Product::create(['name' => 'SALMON','slug' => 'salmon','sku' => 'FF0014','price' => '10','qty' => 1,'category_id' => 6,'status' =>1,'image' => '',]);
        Product::create(['name' => 'PINK SALMON','slug' => 'pink-salmon','sku' => 'FF0015','price' => '10','qty' => 1,'category_id' => 6,'status' =>1,'image' => '',]);
        Product::create(['name' => 'TALAKITOK','slug' => 'talakitok','sku' => 'FF0016','price' => '10','qty' => 1,'category_id' => 6,'status' =>1,'image' => '',]);
        Product::create(['name' => 'TUNA','slug' => 'tuna','sku' => 'FF0017','price' => '10','qty' => 1,'category_id' => 6,'status' =>1,'image' => '',]);
        Product::create(['name' => 'PUSIT','slug' => 'pusit','sku' => 'FF0018','price' => '10','qty' => 1,'category_id' => 6,'status' =>1,'image' => '',]);
        Product::create(['name' => 'HASAHASA','slug' => 'hasahasa','sku' => 'FF0019','price' => '10','qty' => 1,'category_id' => 6,'status' =>1,'image' => '',]);
        Product::create(['name' => 'ESPADA','slug' => 'espada','sku' => 'FF0020','price' => '10','qty' => 1,'category_id' => 6,'status' =>1,'image' => '',]);
        Product::create(['name' => 'SUGPO','slug' => 'sugpo','sku' => 'FF0021','price' => '10','qty' => 1,'category_id' => 6,'status' =>1,'image' => '',]);
        Product::create(['name' => 'SUAHE','slug' => 'suahe','sku' => 'FF0022','price' => '10','qty' => 1,'category_id' => 6,'status' =>1,'image' => '',]);
        Product::create(['name' => 'CRABS','slug' => 'crabs','sku' => 'FF0023','price' => '10','qty' => 1,'category_id' => 6,'status' =>1,'image' => '',]);
        Product::create(['name' => 'TAHONG','slug' => 'tahong','sku' => 'FF0024','price' => '10','qty' => 1,'category_id' => 6,'status' =>1,'image' => '',]);
        Product::create(['name' => 'HALAAN','slug' => 'halaan','sku' => 'FF0025','price' => '10','qty' => 1,'category_id' => 6,'status' =>1,'image' => '',]);
        Product::create(['name' => 'TUYO','slug' => 'tuyo','sku' => 'DF0001','price' => '10','qty' => 1,'category_id' => 7,'status' =>1,'image' => '',]);
        Product::create(['name' => 'DAING','slug' => 'daing','sku' => 'DF0002','price' => '10','qty' => 1,'category_id' => 7,'status' =>1,'image' => '',]);
        Product::create(['name' => 'DRIED SALINAS','slug' => 'dried-salinas','sku' => 'DF0003','price' => '10','qty' => 1,'category_id' => 7,'status' =>1,'image' => '',]);
        Product::create(['name' => 'DILIS SMALL','slug' => 'dilis-small','sku' => 'DF0004','price' => '10','qty' => 1,'category_id' => 7,'status' =>1,'image' => '',]);
        Product::create(['name' => 'DILIS MEDIUM','slug' => 'dilis-medium','sku' => 'DF0005','price' => '10','qty' => 1,'category_id' => 7,'status' =>1,'image' => '',]);
        Product::create(['name' => 'DRIED BONELESS DILIS','slug' => 'dried-boneless dilis','sku' => 'DF0006','price' => '10','qty' => 1,'category_id' => 7,'status' =>1,'image' => '',]);
        Product::create(['name' => 'DRIED PUSIT','slug' => 'dried-pusit','sku' => 'DF0007','price' => '10','qty' => 1,'category_id' => 7,'status' =>1,'image' => '',]);
        Product::create(['name' => 'DRIED TILAPIA','slug' => 'dried-tilapia','sku' => 'DF0008','price' => '10','qty' => 1,'category_id' => 7,'status' =>1,'image' => '',]);
        Product::create(['name' => 'HIBI (DRIED SHRIMP)','slug' => 'hibi-dried-shrimp','sku' => 'DF0009','price' => '10','qty' => 1,'category_id' => 7,'status' =>1,'image' => '',]);
        Product::create(['name' => 'DRIED GALUNGGONG','slug' => 'dried-galunggong','sku' => 'DF0010','price' => '10','qty' => 1,'category_id' => 7,'status' =>1,'image' => '',]);
        Product::create(['name' => 'DRIED BISUGO','slug' => 'dried-bisugo','sku' => 'DF0011','price' => '10','qty' => 1,'category_id' => 7,'status' =>1,'image' => '',]);
        Product::create(['name' => 'LABAHITA','slug' => 'labahita','sku' => 'DF0012','price' => '10','qty' => 1,'category_id' => 7,'status' =>1,'image' => '',]);
        Product::create(['name' => 'DRIED SAPSAP','slug' => 'dried-sapsap','sku' => 'DF0013','price' => '10','qty' => 1,'category_id' => 7,'status' =>1,'image' => '',]);
        Product::create(['name' => 'DANGGIT','slug' => 'danggit','sku' => 'DF0014','price' => '10','qty' => 1,'category_id' => 7,'status' =>1,'image' => '',]);
        Product::create(['name' => 'TINAPA - GALUNGGONG','slug' => 'tinapa-galunggong','sku' => 'DF0015','price' => '10','qty' => 1,'category_id' => 7,'status' =>1,'image' => '',]);
        Product::create(['name' => 'WHOLE CHICKEN','slug' => 'whole-chicken','sku' => 'CH0001','price' => '10','qty' => 1,'category_id' => 9,'status' =>1,'image' => '',]);
        Product::create(['name' => 'ADOBO CUT','slug' => 'adobo-cut','sku' => 'CH0002','price' => '10','qty' => 1,'category_id' => 9,'status' =>1,'image' => '',]);
        Product::create(['name' => 'BREAST','slug' => 'breast','sku' => 'CH0003','price' => '10','qty' => 1,'category_id' => 9,'status' =>1,'image' => '',]);
        Product::create(['name' => 'BREAST FILLET','slug' => 'breast-fillet','sku' => 'CH0004','price' => '10','qty' => 1,'category_id' => 9,'status' =>1,'image' => '',]);
        Product::create(['name' => 'LEG QUARTER','slug' => 'leg-quarter','sku' => 'CH0005','price' => '10','qty' => 1,'category_id' => 9,'status' =>1,'image' => '',]);
        Product::create(['name' => 'THIGH','slug' => 'thigh','sku' => 'CH0006','price' => '10','qty' => 1,'category_id' => 9,'status' =>1,'image' => '',]);
        Product::create(['name' => 'DRUMSTICK','slug' => 'drumstick','sku' => 'CH0007','price' => '10','qty' => 1,'category_id' => 9,'status' =>1,'image' => '',]);
        Product::create(['name' => 'WINGS','slug' => 'wings','sku' => 'CH0008','price' => '10','qty' => 1,'category_id' => 9,'status' =>1,'image' => '',]);
        Product::create(['name' => 'NECK','slug' => 'neck','sku' => 'CH0009','price' => '10','qty' => 1,'category_id' => 9,'status' =>1,'image' => '',]);
        Product::create(['name' => 'LIVER','slug' => 'liver','sku' => 'CH0010','price' => '10','qty' => 1,'category_id' => 9,'status' =>1,'image' => '',]);
        Product::create(['name' => 'GIZZARD','slug' => 'gizzard','sku' => 'CH0011','price' => '10','qty' => 1,'category_id' => 9,'status' =>1,'image' => '',]);
        Product::create(['name' => 'FEET','slug' => 'feet','sku' => 'CH0012','price' => '10','qty' => 1,'category_id' => 9,'status' =>1,'image' => '',]);
        Product::create(['name' => 'TENDERLOIN','slug' => 'beef-tenderloin','sku' => 'BF0001','price' => '10','qty' => 1,'category_id' => 10,'status' =>1,'image' => '',]);
        Product::create(['name' => 'TOP ROUND','slug' => 'beef-top-round','sku' => 'BF0002','price' => '10','qty' => 1,'category_id' => 10,'status' =>1,'image' => '',]);
        Product::create(['name' => 'ROUND STEAK','slug' => 'beef-round-steak','sku' => 'BF0003','price' => '10','qty' => 1,'category_id' => 10,'status' =>1,'image' => '',]);
        Product::create(['name' => 'SIRLOIN','slug' => 'beef-sirloin','sku' => 'BF0004','price' => '10','qty' => 1,'category_id' => 10,'status' =>1,'image' => '',]);
        Product::create(['name' => 'STRIPLOIN','slug' => 'beef-striploin','sku' => 'BF0005','price' => '10','qty' => 1,'category_id' => 10,'status' =>1,'image' => '',]);
        Product::create(['name' => 'T. BONE','slug' => 'beef-t-bone','sku' => 'BF0006','price' => '10','qty' => 1,'category_id' => 10,'status' =>1,'image' => '',]);
        Product::create(['name' => 'BREAST BRISKET','slug' => 'breast brisket','sku' => 'BF0007','price' => '10','qty' => 1,'category_id' => 10,'status' =>1,'image' => '',]);
        Product::create(['name' => 'CANTO','slug' => 'beef-canto','sku' => 'BF0008','price' => '10','qty' => 1,'category_id' => 10,'status' =>1,'image' => '',]);
        Product::create(['name' => 'KNEE CAP','slug' => 'beef-knee-cap','sku' => 'BF0009','price' => '10','qty' => 1,'category_id' => 10,'status' =>1,'image' => '',]);
        Product::create(['name' => 'RIBS','slug' => 'beef-ribs','sku' => 'BF0010','price' => '10','qty' => 1,'category_id' => 10,'status' =>1,'image' => '',]);
        Product::create(['name' => 'SPARERIBS','slug' => 'beef-spareribs','sku' => 'BF0011','price' => '10','qty' => 1,'category_id' => 10,'status' =>1,'image' => '',]);
        Product::create(['name' => 'KALITIRAN/SHOULDER BUTT','slug' => 'kalitiran-shoulder-butt','sku' => 'BF0012','price' => '10','qty' => 1,'category_id' => 10,'status' =>1,'image' => '',]);
        Product::create(['name' => 'KABILUGAN','slug' => 'kabilugan','sku' => 'BF0013','price' => '10','qty' => 1,'category_id' => 10,'status' =>1,'image' => '',]);
        Product::create(['name' => 'PAGONG','slug' => 'pagong','sku' => 'BF0014','price' => '10','qty' => 1,'category_id' => 10,'status' =>1,'image' => '',]);
        Product::create(['name' => 'BULALO','slug' => 'beef-bulalo','sku' => 'BF0015','price' => '10','qty' => 1,'category_id' => 10,'status' =>1,'image' => '',]);
        Product::create(['name' => 'KENCHI BONE-IN','slug' => 'kenchi-bone-in','sku' => 'BF0016','price' => '10','qty' => 1,'category_id' => 10,'status' =>1,'image' => '',]);
        Product::create(['name' => 'BATOK & SOFTBONES','slug' => 'batok-and-softbones','sku' => 'BF0017','price' => '10','qty' => 1,'category_id' => 10,'status' =>1,'image' => '',]);
        Product::create(['name' => 'KADERA','slug' => 'kadera','sku' => 'BF0018','price' => '10','qty' => 1,'category_id' => 10,'status' =>1,'image' => '',]);
        Product::create(['name' => 'NECKBONE','slug' => 'neckbone','sku' => 'BF0019','price' => '10','qty' => 1,'category_id' => 10,'status' =>1,'image' => '',]);
        Product::create(['name' => 'LAMAN','slug' => 'goat-laman','sku' => 'GT0001','price' => '10','qty' => 1,'category_id' => 12,'status' =>1,'image' => '',]);
        Product::create(['name' => 'UP & DOWN SET (ULO/PAA)','slug' => 'up-and-down-set-ulo-paa','sku' => 'GT0002','price' => '10','qty' => 1,'category_id' => 12,'status' =>1,'image' => '',]);
        Product::create(['name' => 'PAPAITAN','slug' => 'goat-papaitan','sku' => 'GT0003','price' => '10','qty' => 1,'category_id' => 12,'status' =>1,'image' => '',]);
        Product::create(['name' => 'BULALO','slug' => 'carabao-bulalo','sku' => 'CB0004','price' => '10','qty' => 1,'category_id' => 11,'status' =>1,'image' => '',]);
        Product::create(['name' => 'SOFT BONE','slug' => 'soft bone','sku' => 'CB0005','price' => '10','qty' => 1,'category_id' => 11,'status' =>1,'image' => '',]);
        Product::create(['name' => 'LAMAN','slug' => 'carabao-laman','sku' => 'CB0006','price' => '10','qty' => 1,'category_id' => 11,'status' =>1,'image' => '',]);
        Product::create(['name' => 'BATOK','slug' => 'batok','sku' => 'CB0007','price' => '10','qty' => 1,'category_id' => 11,'status' =>1,'image' => '',]);
        Product::create(['name' => 'SIRLOIN','slug' => 'sirloin','sku' => 'CB0008','price' => '10','qty' => 1,'category_id' => 11,'status' =>1,'image' => '',]);
        Product::create(['name' => 'TENDERLOIN','slug' => 'tenderloin','sku' => 'CB0009','price' => '10','qty' => 1,'category_id' => 11,'status' =>1,'image' => '',]);
        Product::create(['name' => 'RIBS','slug' => 'ribs','sku' => 'CB0010','price' => '10','qty' => 1,'category_id' => 11,'status' =>1,'image' => '',]);
        Product::create(['name' => 'BRISKET','slug' => 'brisket','sku' => 'CB0011','price' => '10','qty' => 1,'category_id' => 11,'status' =>1,'image' => '',]);
        Product::create(['name' => 'PAPAITAN','slug' => 'papaitan','sku' => 'CB0012','price' => '10','qty' => 1,'category_id' => 11,'status' =>1,'image' => '',]);
        Product::create(['name' => 'GOTO','slug' => 'goto','sku' => 'CB0013','price' => '10','qty' => 1,'category_id' => 11,'status' =>1,'image' => '',]);
        Product::create(['name' => 'PATA HARAP (WHOLE FOR CRISPY PATA)','slug' => 'pata-harap-whole for crispy pata','sku' => 'PK0001','price' => '10','qty' => 1,'category_id' => 13,'status' =>1,'image' => '',]);
        Product::create(['name' => 'PATA HARAP (CHOPPED)','slug' => 'pata-harap-chopped','sku' => 'PK0002','price' => '10','qty' => 1,'category_id' => 13,'status' =>1,'image' => '',]);
        Product::create(['name' => 'PATA LIKOD (CHOPPED)','slug' => 'pata-likod-chopped','sku' => 'PK0003','price' => '10','qty' => 1,'category_id' => 13,'status' =>1,'image' => '',]);
        Product::create(['name' => 'ULO (WHOLE)','slug' => 'ulo-whole','sku' => 'PK0004','price' => '10','qty' => 1,'category_id' => 13,'status' =>1,'image' => '',]);
        Product::create(['name' => 'ADOBO CUT','slug' => 'pork-adobo-cut','sku' => 'PK0005','price' => '10','qty' => 1,'category_id' => 13,'status' =>1,'image' => '',]);
        Product::create(['name' => 'SINIGANG CUT','slug' => 'pork-sinigang-cut','sku' => 'PK0006','price' => '10','qty' => 1,'category_id' => 13,'status' =>1,'image' => '',]);
        Product::create(['name' => 'IGADO CUT','slug' => 'pork-igado-cut','sku' => 'PK0007','price' => '10','qty' => 1,'category_id' => 13,'status' =>1,'image' => '',]);
        Product::create(['name' => 'BICOL EXPRESS CUT','slug' => 'pork-bicol-express-cut','sku' => 'PK0008','price' => '10','qty' => 1,'category_id' => 13,'status' =>1,'image' => '',]);
        Product::create(['name' => 'STEAK CUT','slug' => 'pork-steak-cut','sku' => 'PK0009','price' => '10','qty' => 1,'category_id' => 13,'status' =>1,'image' => '',]);
        Product::create(['name' => 'BBQ CUT','slug' => 'pork-bbq-cut','sku' => 'PK0010','price' => '10','qty' => 1,'category_id' => 13,'status' =>1,'image' => '',]);
        Product::create(['name' => 'DINUGUAN CUT','slug' => 'pork-dinuguan-cut','sku' => 'PK0011','price' => '10','qty' => 1,'category_id' => 13,'status' =>1,'image' => '',]);
        Product::create(['name' => 'MENUDO CUT','slug' => 'pork-menudo-cut','sku' => 'PK0012','price' => '10','qty' => 1,'category_id' => 13,'status' =>1,'image' => '',]);
        Product::create(['name' => 'PORK CUBES','slug' => 'pork-cubes','sku' => 'PK0013','price' => '10','qty' => 1,'category_id' => 13,'status' =>1,'image' => '',]);
        Product::create(['name' => 'GINILING','slug' => 'pork-giniling','sku' => 'PK0014','price' => '10','qty' => 1,'category_id' => 13,'status' =>1,'image' => '',]);
        Product::create(['name' => 'PORKCHOP','slug' => 'porkchop','sku' => 'PK0015','price' => '10','qty' => 1,'category_id' => 13,'status' =>1,'image' => '',]);
        Product::create(['name' => 'LIEMPO (LECHON KAWALI)','slug' => 'liempo-lechon-kawali','sku' => 'PK0016','price' => '10','qty' => 1,'category_id' => 13,'status' =>1,'image' => '',]);
        Product::create(['name' => 'LIEMPO (INIHAW CUT)','slug' => 'liempo-inihaw-cut','sku' => 'PK0017','price' => '10','qty' => 1,'category_id' => 13,'status' =>1,'image' => '',]);
        Product::create(['name' => 'RIBS (CALDERETA/SINIGANG CUT)','slug' => 'ribs-caldereta-sinigang-cut','sku' => 'PK0018','price' => '10','qty' => 1,'category_id' => 13,'status' =>1,'image' => '',]);
        Product::create(['name' => 'PECHO (SPECIAL RIBS)','slug' => 'pecho-special-ribs','sku' => 'PK0019','price' => '10','qty' => 1,'category_id' => 13,'status' =>1,'image' => '',]);
        Product::create(['name' => 'LOMO','slug' => 'pork-lomo','sku' => 'PK0020','price' => '10','qty' => 1,'category_id' => 13,'status' =>1,'image' => '',]);
        Product::create(['name' => 'LIVER','slug' => 'pork-liver','sku' => 'PK0021','price' => '10','qty' => 1,'category_id' => 13,'status' =>1,'image' => '',]);
        Product::create(['name' => 'REPOLYO','slug' => 'repolyo','sku' => 'VB0001','price' => '10','qty' => 1,'category_id' => 2,'status' =>1,'image' => '',]);
        Product::create(['name' => 'CARROTS','slug' => 'carrots','sku' => 'VB0002','price' => '10','qty' => 1,'category_id' => 2,'status' =>1,'image' => '',]);
        Product::create(['name' => 'PECHAY BAGUIO','slug' => 'pechay-baguio','sku' => 'VB0003','price' => '10','qty' => 1,'category_id' => 2,'status' =>1,'image' => '',]);
        Product::create(['name' => 'CHERRY TOMATOES','slug' => 'cherry-tomatoes','sku' => 'VB0004','price' => '10','qty' => 1,'category_id' => 2,'status' =>1,'image' => '',]);
        Product::create(['name' => 'LETTUCE GREEN','slug' => 'lettuce-green','sku' => 'VB0005','price' => '10','qty' => 1,'category_id' => 2,'status' =>1,'image' => '',]);
        Product::create(['name' => 'ZUCCHINI','slug' => 'zucchini','sku' => 'VB0006','price' => '10','qty' => 1,'category_id' => 2,'status' =>1,'image' => '',]);
        Product::create(['name' => 'SPINACH','slug' => 'spinach','sku' => 'VB0007','price' => '10','qty' => 1,'category_id' => 2,'status' =>1,'image' => '',]);
        Product::create(['name' => 'LETTUCE RED','slug' => 'lettuce-red','sku' => 'VB0008','price' => '10','qty' => 1,'category_id' => 2,'status' =>1,'image' => '',]);
        Product::create(['name' => 'BAGUIO RADISH','slug' => 'baguio-radish','sku' => 'VB0009','price' => '10','qty' => 1,'category_id' => 2,'status' =>1,'image' => '',]);
        Product::create(['name' => 'POTATO','slug' => 'potato','sku' => 'VB0010','price' => '10','qty' => 1,'category_id' => 2,'status' =>1,'image' => '',]);
        Product::create(['name' => 'ONION LEEKS','slug' => 'onion-leeks','sku' => 'VB0011','price' => '10','qty' => 1,'category_id' => 2,'status' =>1,'image' => '',]);
        Product::create(['name' => 'GREEN BELLPEPPER','slug' => 'green-bellpepper','sku' => 'VB0012','price' => '10','qty' => 1,'category_id' => 2,'status' =>1,'image' => '',]);
        Product::create(['name' => 'CUCUMBER','slug' => 'cucumber','sku' => 'VB0013','price' => '10','qty' => 1,'category_id' => 2,'status' =>1,'image' => '',]);
        Product::create(['name' => 'CAULIFLOWER','slug' => 'cauliflower','sku' => 'VB0014','price' => '10','qty' => 1,'category_id' => 2,'status' =>1,'image' => '',]);
        Product::create(['name' => 'BROCCOLI','slug' => 'broccoli','sku' => 'VB0015','price' => '10','qty' => 1,'category_id' => 2,'status' =>1,'image' => '',]);
        Product::create(['name' => 'BAGUIO BEANS','slug' => 'baguio-beans','sku' => 'VB0016','price' => '10','qty' => 1,'category_id' => 2,'status' =>1,'image' => '',]);
        Product::create(['name' => 'LETTUCE ICEBERG','slug' => 'lettuce-iceberg','sku' => 'VB0017','price' => '10','qty' => 1,'category_id' => 2,'status' =>1,'image' => '',]);
        Product::create(['name' => 'PARSLEY CURLY','slug' => 'parsley-curly','sku' => 'VB0018','price' => '10','qty' => 1,'category_id' => 2,'status' =>1,'image' => '',]);
        Product::create(['name' => 'LETTUCE ROMAINE','slug' => 'lettuce-romaine','sku' => 'VB0019','price' => '10','qty' => 1,'category_id' => 2,'status' =>1,'image' => '',]);
        Product::create(['name' => 'RED BELLPEPPER ','slug' => 'red-bellpepper ','sku' => 'VB0020','price' => '10','qty' => 1,'category_id' => 2,'status' =>1,'image' => '',]);
        Product::create(['name' => 'YELLOW BELLPEPPER','slug' => 'yellow-bellpepper','sku' => 'VB0021','price' => '10','qty' => 1,'category_id' => 2,'status' =>1,'image' => '',]);
        Product::create(['name' => 'SAYOTE','slug' => 'sayote','sku' => 'VB0022','price' => '10','qty' => 1,'category_id' => 2,'status' =>1,'image' => '',]);
        Product::create(['name' => 'SWEET PEAS','slug' => 'sweet-peas','sku' => 'VB0023','price' => '10','qty' => 1,'category_id' => 2,'status' =>1,'image' => '',]);
        Product::create(['name' => 'GABI','slug' => 'gabi','sku' => 'VB0024','price' => '10','qty' => 1,'category_id' => 2,'status' =>1,'image' => '',]);
        Product::create(['name' => 'TARO','slug' => 'taro','sku' => 'VB0025','price' => '10','qty' => 1,'category_id' => 2,'status' =>1,'image' => '',]);
        Product::create(['name' => 'ASPARAGUS','slug' => 'asparagus','sku' => 'VB0026','price' => '10','qty' => 1,'category_id' => 2,'status' =>1,'image' => '',]);
        Product::create(['name' => 'CELERY','slug' => 'celery','sku' => 'VB0027','price' => '10','qty' => 1,'category_id' => 2,'status' =>1,'image' => '',]);
        Product::create(['name' => 'TALONG','slug' => 'talong','sku' => 'VT0001','price' => '10','qty' => 1,'category_id' => 3,'status' =>1,'image' => '',]);
        Product::create(['name' => 'AMPALAYA','slug' => 'ampalaya','sku' => 'VT0002','price' => '10','qty' => 1,'category_id' => 3,'status' =>1,'image' => '',]);
        Product::create(['name' => 'OKRA','slug' => 'okra','sku' => 'VT0003','price' => '10','qty' => 1,'category_id' => 3,'status' =>1,'image' => '',]);
        Product::create(['name' => 'SITAW','slug' => 'sitaw','sku' => 'VT0004','price' => '10','qty' => 1,'category_id' => 3,'status' =>1,'image' => '',]);
        Product::create(['name' => 'KANGKONG','slug' => 'baguio-kangkong','sku' => 'VT0005','price' => '10','qty' => 1,'category_id' => 3,'status' =>1,'image' => '',]);
        Product::create(['name' => 'LABANIS','slug' => 'labanis','sku' => 'VT0006','price' => '10','qty' => 1,'category_id' => 3,'status' =>1,'image' => '',]);
        Product::create(['name' => 'SILING LABUYO','slug' => 'siling-labuyo','sku' => 'VT0007','price' => '10','qty' => 1,'category_id' => 3,'status' =>1,'image' => '',]);
        Product::create(['name' => 'TALONG BILOG','slug' => 'talong-bilog','sku' => 'VT0008','price' => '10','qty' => 1,'category_id' => 3,'status' =>1,'image' => '',]);
        Product::create(['name' => 'TALBOS NG KAMOTE','slug' => 'talbos-ng-kamote','sku' => 'VT0009','price' => '10','qty' => 1,'category_id' => 3,'status' =>1,'image' => '',]);
        Product::create(['name' => 'SALUYOT','slug' => 'saluyot','sku' => 'VT0010','price' => '10','qty' => 1,'category_id' => 3,'status' =>1,'image' => '',]);
        Product::create(['name' => 'ALUGBATI','slug' => 'alugbati','sku' => 'VT0011','price' => '10','qty' => 1,'category_id' => 3,'status' =>1,'image' => '',]);
        Product::create(['name' => 'BUNGA MALUNGGAY','slug' => 'bunga-malunggay','sku' => 'VT0012','price' => '10','qty' => 1,'category_id' => 3,'status' =>1,'image' => '',]);
        Product::create(['name' => 'KAMATIS','slug' => 'kamatis','sku' => 'VT0013','price' => '10','qty' => 1,'category_id' => 3,'status' =>1,'image' => '',]);
        Product::create(['name' => 'KINCHAY','slug' => 'kinchay','sku' => 'VT0014','price' => '10','qty' => 1,'category_id' => 3,'status' =>1,'image' => '',]);
        Product::create(['name' => 'LOYA','slug' => 'loya','sku' => 'VT0015','price' => '10','qty' => 1,'category_id' => 3,'status' =>1,'image' => '',]);
        Product::create(['name' => 'PIPINO','slug' => 'pipino','sku' => 'VT0016','price' => '10','qty' => 1,'category_id' => 3,'status' =>1,'image' => '',]);
        Product::create(['name' => 'UPO','slug' => 'upo','sku' => 'VT0017','price' => '10','qty' => 1,'category_id' => 3,'status' =>1,'image' => '',]);
        Product::create(['name' => 'SIGARILYAS','slug' => 'sigarilyas','sku' => 'VT0018','price' => '10','qty' => 1,'category_id' => 3,'status' =>1,'image' => '',]);
        Product::create(['name' => 'BATAW','slug' => 'bataw','sku' => 'VT0019','price' => '10','qty' => 1,'category_id' => 3,'status' =>1,'image' => '',]);
        Product::create(['name' => 'KAMOTE','slug' => 'kamote','sku' => 'VT0020','price' => '10','qty' => 1,'category_id' => 3,'status' =>1,'image' => '',]);
        Product::create(['name' => 'PATANI','slug' => 'patani','sku' => 'VT0021','price' => '10','qty' => 1,'category_id' => 3,'status' =>1,'image' => '',]);
        Product::create(['name' => 'SINGKAMAS','slug' => 'singkamas','sku' => 'VT0022','price' => '10','qty' => 1,'category_id' => 3,'status' =>1,'image' => '',]);
        Product::create(['name' => 'ALOCON','slug' => 'alocon','sku' => 'VT0023','price' => '10','qty' => 1,'category_id' => 3,'status' =>1,'image' => '',]);
        Product::create(['name' => 'PATATAS','slug' => 'patatas','sku' => 'VT0024','price' => '10','qty' => 1,'category_id' => 3,'status' =>1,'image' => '',]);
        Product::create(['name' => 'PATOLA','slug' => 'patola','sku' => 'VT0025','price' => '10','qty' => 1,'category_id' => 3,'status' =>1,'image' => '',]);
        Product::create(['name' => 'KALABASA','slug' => 'kalabasa','sku' => 'VT0026','price' => '10','qty' => 1,'category_id' => 3,'status' =>1,'image' => '',]);
        Product::create(['name' => 'MUSTASA','slug' => 'mustasa','sku' => 'VT0027','price' => '10','qty' => 1,'category_id' => 3,'status' =>1,'image' => '',]);
        Product::create(['name' => 'MALUNGAY','slug' => 'malungay','sku' => 'VT0028','price' => '10','qty' => 1,'category_id' => 3,'status' =>1,'image' => '',]);
        Product::create(['name' => 'KANGKONG','slug' => 'kangkong','sku' => 'VT0029','price' => '10','qty' => 1,'category_id' => 3,'status' =>1,'image' => '',]);
        Product::create(['name' => 'PUSO PANG KARE-KARE','slug' => 'puso-pang-kare-kare','sku' => 'VT0030','price' => '10','qty' => 1,'category_id' => 3,'status' =>1,'image' => '',]);
        Product::create(['name' => 'PUSO PANG GULAY','slug' => 'puso-pang-gulay','sku' => 'VT0031','price' => '10','qty' => 1,'category_id' => 3,'status' =>1,'image' => '',]);
        Product::create(['name' => 'APPLE','slug' => 'apple','sku' => 'FR0001','price' => '10','qty' => 1,'category_id' => 4,'status' =>1,'image' => '',]);
        Product::create(['name' => 'GRAPES','slug' => 'grapes','sku' => 'FR0002','price' => '10','qty' => 1,'category_id' => 4,'status' =>1,'image' => '',]);
        Product::create(['name' => 'MANGO','slug' => 'mango','sku' => 'FR0003','price' => '10','qty' => 1,'category_id' => 4,'status' =>1,'image' => '',]);
        Product::create(['name' => 'LANZONES','slug' => 'lanzones','sku' => 'FR0004','price' => '10','qty' => 1,'category_id' => 4,'status' =>1,'image' => '',]);
        Product::create(['name' => 'LONGGAN','slug' => 'longgan','sku' => 'FR0005','price' => '10','qty' => 1,'category_id' => 4,'status' =>1,'image' => '',]);
        Product::create(['name' => 'LAKATAN','slug' => 'lakatan','sku' => 'FR0006','price' => '10','qty' => 1,'category_id' => 4,'status' =>1,'image' => '',]);
        Product::create(['name' => 'LATUNDAN','slug' => 'latundan','sku' => 'FR0007','price' => '10','qty' => 1,'category_id' => 4,'status' =>1,'image' => '',]);
        Product::create(['name' => 'SENYORITA','slug' => 'senyorita','sku' => 'FR0008','price' => '10','qty' => 1,'category_id' => 4,'status' =>1,'image' => '',]);
        Product::create(['name' => 'GUYABANO','slug' => 'guyabano','sku' => 'FR0009','price' => '10','qty' => 1,'category_id' => 4,'status' =>1,'image' => '',]);
        Product::create(['name' => 'PAPAYA','slug' => 'papaya','sku' => 'FR0010','price' => '10','qty' => 1,'category_id' => 4,'status' =>1,'image' => '',]);
        Product::create(['name' => 'ATIS','slug' => 'atis','sku' => 'FR0011','price' => '10','qty' => 1,'category_id' => 4,'status' =>1,'image' => '',]);
        Product::create(['name' => 'SANTOL','slug' => 'santol','sku' => 'FR0012','price' => '10','qty' => 1,'category_id' => 4,'status' =>1,'image' => '',]);
        Product::create(['name' => 'DRAGON FRUIT','slug' => 'dragon-fruit','sku' => 'FR0013','price' => '10','qty' => 1,'category_id' => 4,'status' =>1,'image' => '',]);
        Product::create(['name' => 'MANGOSTEEN','slug' => 'mangosteen','sku' => 'FR0014','price' => '10','qty' => 1,'category_id' => 4,'status' =>1,'image' => '',]);
        Product::create(['name' => 'KIWI','slug' => 'kiwi','sku' => 'FR0015','price' => '10','qty' => 1,'category_id' => 4,'status' =>1,'image' => '',]);
        Product::create(['name' => 'SUHA','slug' => 'suha','sku' => 'FR0016','price' => '10','qty' => 1,'category_id' => 4,'status' =>1,'image' => '',]);
        Product::create(['name' => 'AVOCADO','slug' => 'avocado','sku' => 'FR0017','price' => '10','qty' => 1,'category_id' => 4,'status' =>1,'image' => '',]);
        Product::create(['name' => 'INDIAN MANGO','slug' => 'indian-mango','sku' => 'FR0018','price' => '10','qty' => 1,'category_id' => 4,'status' =>1,'image' => '',]);
        Product::create(['name' => 'RAMBUTAN','slug' => 'rambutan','sku' => 'FR0019','price' => '10','qty' => 1,'category_id' => 4,'status' =>1,'image' => '',]);
        Product::create(['name' => 'DURIAN','slug' => 'durian','sku' => 'FR0020','price' => '10','qty' => 1,'category_id' => 4,'status' =>1,'image' => '',]);
        Product::create(['name' => 'MARANG','slug' => 'marang','sku' => 'FR0021','price' => '10','qty' => 1,'category_id' => 4,'status' =>1,'image' => '',]);
        Product::create(['name' => 'DALANDAN','slug' => 'dalandan','sku' => 'FR0022','price' => '10','qty' => 1,'category_id' => 4,'status' =>1,'image' => '',]);
        Product::create(['name' => 'PAKWAN','slug' => 'pakwan','sku' => 'FR0023','price' => '10','qty' => 1,'category_id' => 4,'status' =>1,'image' => '',]);
        Product::create(['name' => 'MELON','slug' => 'melon','sku' => 'FR0024','price' => '10','qty' => 1,'category_id' => 4,'status' =>1,'image' => '',]);
        Product::create(['name' => 'LEMON','slug' => 'lemon','sku' => 'FR0025','price' => '10','qty' => 1,'category_id' => 4,'status' =>1,'image' => '',]);
        Product::create(['name' => 'PERAS','slug' => 'peras','sku' => 'FR0026','price' => '10','qty' => 1,'category_id' => 4,'status' =>1,'image' => '',]);
        Product::create(['name' => 'CHICO','slug' => 'chico','sku' => 'FR0027','price' => '10','qty' => 1,'category_id' => 4,'status' =>1,'image' => '',]);
        Product::create(['name' => 'STRAWBERRY','slug' => 'strawberry','sku' => 'FR0028','price' => '10','qty' => 1,'category_id' => 4,'status' =>1,'image' => '',]);
        Product::create(['name' => 'SABA','slug' => 'saba','sku' => 'FR0029','price' => '10','qty' => 1,'category_id' => 4,'status' =>1,'image' => '',]);
    }
}
